inputs:
  os:
    required: true
runs:
  using: "composite"
  steps:
    - name: ut
      id: ut
      shell: bash
      continue-on-error: true
      run: |
        if [ ${{ inputs.os }} = "macOS" ]; then
          scheme=Mac-Tests
          destination="platform=macOS,arch=arm64,name=My Mac"
        else
          scheme=iOS-Tests
          destination="platform=iOS Simulator,name=$device,OS=${{ inputs.os }}"
        fi
        xcodebuild -workspace GitHubActions.xcworkspace \
                    -scheme $scheme \
                    -destination "$destination" \
                    -resultBundlePath ~/GitHubActionsTests-${{ inputs.os }}.xcresult \
                    -clonedSourcePackagesDirPath ~/SourcePackages \
                    -testLanguage ja \
                    -skipMacroValidation \
                    -skipPackagePluginValidation \
                    test
    - name: Upload xcresult
      uses: actions/upload-artifact@v4
      with:
        name: GitHubActionsTests-${{ inputs.os }}-${{ github.run_number }}.xcresult
        path: ~/GitHubActionsTests-${{ inputs.os }}.xcresult
        retention-days: 1
    - name: exit
      shell: bash
      run: |
        if [ "${{ steps.ut.outcome }}" = "success" ]; then
          exit 0
        else
          exit 1
        fi