name: Status Check
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: test
        run: echo "test"
      - uses: actions/checkout@v4
      - name: set sub workflow status pending
        run: |
          git log --oneline --graph --decorate --all
