name: CI
on:
  pull_request:
    types: [synchronize]
  workflow_dispatch:

jobs:
  queue:
    if: github.event_name == 'pull_request'
    name: queue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'review',
              head_sha: '${{ github.event.pull_request.head.sha }}',
              status: 'queued'
            })
  workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: lint
        id: lint
        continue-on-error: true
        run: exit 0
      - name: ut
        id: ut
        continue-on-error: true
        run: exit 0
      - uses: actions/github-script@v7
        with:
          script: |
            const list = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.ref }}',
              check_name: 'review',
              filter: 'latest'
            });
            const id = list.data.check_runs[0].id;
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: id,
              status: 'completed',
              conclusion: ${{ steps.lint.outcome == 'success' }} && ${{ steps.ut.outcome == 'success' }} ? 'success' : 'failure'
            })
