name: Status Check
on: workflow_dispatch

jobs:
  ci:
    # if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: something test1
        id: ut
        run: exit 0
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: run tests
          status: completed
      # - name: get sha from PR number and save output
      #   id: get-sha
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const pr = await github.rest.pulls.get({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: 5
      #       })
      #       console.log('PR Head sha: ' + pr.data.head.sha)
      #       core.setOutput('sha', pr.data.head.sha)
      # - name: ubuntu-latest 
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #         const pr = await github.rest.pulls.get({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           pull_number: 5
      #         })
      #         console.log('PR Head sha: ' + pr.data.head.sha)
      #         core.setOutput('sha', pr.data.head.sha)
      #         github.rest.checks.create({
      #           name: 'run tests',
      #           head_sha: pr.data.head.sha,
      #           status: 'completed',
      #           conclusion: '${{ steps.ut.outcome }}',
      #           output: {
      #             title: 'Run tests',
      #             summary: 'Results: ${{ steps.ut.outcome }}'
      #           },
      #           owner: context.repo.owner,
      #           repo: context.repo.repo
      #         })
