name: Status Check
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
      - uses: actions/checkout@v4
      - name: set sub workflow status pending
        run: |
          git log --oneline --graph --decorate --all

          latest_main_run_commit_hash=$(git rev-parse HEAD)
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sk409/GitHubActionsTests/statuses/${latest_main_run_commit_hash} \
            -f state=pending \
            -f description='test description' \
            -f context='test context'
