# name: CI
# on:
#   pull_request:
#     types: [opened, synchronize]
# jobs:
#   review:
#     name: review
#     runs-on: ubuntu-latest
#     steps:
#       - name: Failure
#         run: exit 1
      # - uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.checks.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         name: 'review',
      #         head_sha: '${{ github.event.pull_request.head.sha }}',
      #         status: 'queued'
      #       })