name: CI
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  f:
    name: f
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  review:
    name: review
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"
      # - uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.checks.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         name: 'review',
      #         head_sha: '${{ github.event.pull_request.head.sha }}',
      #         status: 'queued'
      #       })