name: CI
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      checkRunID: ${{ steps.setup.outputs.result }}
    steps:
      - name: Set Up
        id: setup
        uses: actions/github-script@v7
        with:
          script: |
            const list = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.ref }}',
              check_name: 'review',
              filter: 'latest'
            });
            const checkRunID = list.data.check_runs[0].id;
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: checkRunID,
              status: 'in_progress'
            })
            return {
              checkRunID
            }
  format:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Format
        run: |
          brew install swift-format
          swift-format format -i $(git diff origin/main..${{ github.ref }})
      - name: Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'generated'
          git push
        if: steps.diff.outcome == 'failure'
  lint:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: |
          brew install swift-format
          swift-format lint -s $(git diff origin/main..${{ github.ref }})
  ut:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        iOS: ["15.0", "16.0", "17.5"]
    steps:
      - name: Delete Xcodes
        run: |
          rm -rf /Applications/Xcode_16.1_beta.app \
                 /Applications/Xcode_16_beta_6.app \
                 /Applications/Xcode_15.4.app \
                 /Applications/Xcode_15.2.app \
                 /Applications/Xcode_15.1.app \
                 /Applications/Xcode_15.0.1.app \
                 /Applications/Xcode_14.3.1.app
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
      - name: Install simulators
        if: ${{ matrix.iOS != '17.5' }}
        run: sudo xcodes runtimes install "iOS ${{ matrix.iOS }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: UT
        run: |
          if [ ${{ matrix.iOS }} = "15.0" ]; then
            device="iPhone 13 Pro"
          else
            device="iPhone 14 Pro"
          fi
          xcodebuild -workspace GitHubActions.xcworkspace \
                     -scheme GitHubActionsTests \
                     -destination "platform=iOS Simulator,name=$device,OS=${{ matrix.iOS }}" \
                     test
  completed:
    runs-on: ubuntu-latest
    if: always()
    needs: [setup, lint, ut]
    steps:
      - name: Completed
        uses: actions/github-script@v7
        with:
          script: |
            console.log(needs.setup)
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ needs.setup.checkRunID }},
              status: 'completed',
              conclusion: ${{ needs.lint.result == 'success' }} && ${{ needs.iOS15.result == 'success' }} ? 'success' : 'failure'
            })
    