name: CI
on:
  workflow_dispatch:

jobs:
  in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: id
        id: id
        uses: actions/github-script@v7
        with:
          script: |
            const list = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.ref }}',
              check_name: 'review',
              filter: 'latest'
            });
            const id = list.data.check_runs[0].id;
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: id,
              status: 'in_progress'
            })
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: exit 0
  ut:
    runs-on: ubuntu-latest
    steps:
      - name: ut
        run: exit 0
  update:
    runs-on: ubuntu-latest
    needs: [lint, ut]
    steps:
      - name: update
        uses: actions/github-script@v7
        with:
          script: |
            const list = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.ref }}',
              check_name: 'review',
              filter: 'latest'
            });
            const id = list.data.check_runs[0].id;
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: id,
              status: 'completed',
              conclusion: ${{ needs.lint.result == 'success' }} && ${{ needs.ut.result == 'success' }} ? 'success' : 'failure'
            })
    