name: Review
on:
  workflow_dispatch:

jobs:
  ci:
    name: review
    runs-on: ubuntu-latest
    steps:
      - name: something test1
        id: ut
        run: exit 0
      - uses: actions/github-script@v7
        with:
          script: |
            const list = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'feature/pr6',
              check_name: 'review',
              filter: 'latest'
            });
            const id = list.data.check_runs[0].id;
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: id
            })